# This file is Free Software under the Apache-2.0 License
# without warranty, see README.md and LICENSES/Apache-2.0.txt for details.
#
# SPDX-License-Identifier: Apache-2.0
#
# SPDX-FileCopyrightText: 2025 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
# Software-Engineering: 2025 Intevation GmbH <https://intevation.de>

name: Go

on:
  push:
    paths:
      - "**.go"
  pull_request:
    paths:
      - "**.go"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all tags are fetched

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Build
        run: make

      - name: vet
        run: go vet ./...

      - uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-flags: "-l -d"

      - name: Revive Action
        uses: morphy2k/revive-action@v2.5.1

